dependencies {
    compileOnly("org.jetbrains:annotations:24.1.0")

    // kotlin
    runtimeOnly(forge.kotlinforforge)
    compileOnly(forge.kotlinforforge)
    api(forge.kotlinforforge)
    jarJar(forge.kotlinforforge)

    // Runtime Recipe Viewers - uncomment whichever one you want to use //
    // modRuntimeOnly(forge.emi)
    modRuntimeOnly(forge.bundles.jei)
    // modRuntimeOnly(forge.bundles.rei.runtime)

    // GTM
    modImplementation(forge.gtm)
    modImplementation(forge.ldlib)

    // Shimmer
    modCompileOnly(forge.shimmer)

    // Registrate
    modImplementation(forge.registrate)

    // Create and its dependencies
    modImplementation(variantOf(forge.create) { classifier("all") })// { transitive = false }
    modImplementation(forge.flywheel.forge)
    modImplementation(forge.ponder)

    // Recipe Viewers
    modCompileOnly(forge.bundles.jei)
    modCompileOnly(forge.bundles.rei)
    modCompileOnly(forge.emi)

    // Jade
    modCompileOnly(forge.jade)

    // Mixin (& Extras)
    annotationProcessor(variantOf(libs.mixin) { classifier("processor") })
    annotationProcessor(forge.mixinextras.common)
    compileOnly(forge.mixinextras.common)
    compileOnly(forge.mixinextras)

    // Configuration
    modImplementation(forge.configuration)

    // ae2
    modImplementation(forge.ae2)

    // AdAstra
    modImplementation(forge.ad.astra)
    modImplementation(forge.resourcefullib)
    modImplementation(forge.resourcefulconfig)
    modImplementation(forge.botarium)

    //others
    modImplementation(forge.supplementaries)
    modImplementation(forge.cc.tweaked)
    modImplementation(forge.selene)
    modImplementation(forge.botania)
    modImplementation(forge.curios)
    modImplementation(forge.patchouli)
}